defaults:
  - user: shannon
  - experiments: PlanTmedium3x
  - eval: longest6

save_explainability_viz: False

host: localhost
port: 2020
trafficManagerPort: 8020
trafficManagerSeed: 0
dataProviderSeed: 0
debug: 0
viz: 0
record: ''
timeout: 600.0

hydra:
  run:
    dir: ${experiments.agent_root}/${save_path}

repetitions: 1
track: MAP
resume: 1
save_path: test_eval_049
log_save_path: result_logs
checkpoint_file: results.json
checkpoint: ${experiments.agent_root}/${save_path}/${checkpoint_file}

DEBUG_CHALLENGE: 0
CUDA_VISIBLE_DEVICES: 0